// Generated by Wrangler on Sun Jun 02 2024 11:12:08 GMT+0800 (中国标准时间)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  AUTH_SECRET: 'MohY0/2zSQw/psWEnejC2ka3Al0oifvY4YjOkUaFfnI='
  AUTH_URL: 'https://ada-note.pages.dev'
  DB: D1Database
}
