// Generated by Wrangler on Sun Jun 02 2024 11:12:08 GMT+0800 (中国标准时间)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  AUTH_SECRET: string
  AUTH_URL: string
  DB: D1Database
  IMAGE_BUCKET: R2Bucket
}
